version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: prismjs
    versions:
    - 1.22.0
    - 1.23.0
  - dependency-name: "@vuepress/plugin-search"
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-nprogress"
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-medium-zoom"
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-blog"
    versions:
    - 1.9.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  registries:
  - npm-registry-npm-pkg-github-com
